In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [53]:
# Define the industries of GICS classification
gics_industries = {
    "101010": "Energy Equipment & Services",
    "101020": "Oil, Gas & Consumable Fuels",
    "151010": "Chemicals",
    "151020": "Construction Materials",
    "151030": "Containers & Packaging",
    "151040": "Metals & Mining",
    "151050": "Paper & Forest Products",
    "201010": "Aerospace & Defense",
    "201020": "Building Products",
    "201030": "Construction & Engineering",
    "201040": "Electrical Equipment",
    "201050": "Industrial Conglomerates",
    "201060": "Machinery",
    "201070": "Trading Companies & Distributors",
    "202010": "Commercial Services & Supplies",
    "202020": "Professional Services",
    "203010": "Air Freight & Logistics",
    "203020": "Passenger Airlines",
    "203030": "Marine Transportation",
    "203040": "Ground Transportation",
    "203050": "Transportation Infrastructure",
    "251010": "Automobile Components",
    "251020": "Automobiles",
    "252010": "Household Durables",
    "252020": "Leisure Products",
    "252030": "Textiles, Apparel & Luxury Goods",
    "253010": "Hotels, Restaurants & Leisure",
    "253020": "Diversified Consumer Services",
    "255010": "Distributors",
    "255030": "Broadline Retail",
    "255040": "Specialty Retail",
    "301010": "Consumer Staples Distribution & Retail",
    "302010": "Beverages",
    "302020": "Food Products",
    "302030": "Tobacco",
    "303010": "Household Products",
    "303020": "Personal Care Products",
    "351010": "Health Care Equipment & Supplies",
    "351020": "Health Care Providers & Services",
    "351030": "Health Care Technology",
    "352010": "Biotechnology",
    "352020": "Pharmaceuticals",
    "352030": "Life Sciences Tools & Services",
    "401010": "Banks",
    "402010": "Financial Services",
    "402020": "Consumer Finance",
    "402030": "Capital Markets",
    "402040": "Mortgage Real Estate Investment Trusts (REITs)",
    "403010": "Insurance",
    "451020": "IT Services",
    "451030": "Software",
    "452010": "Communications Equipment",
    "452020": "Technology Hardware, Storage & Peripherals",
    "452030": "Electronic Equipment, Instruments & Components",
    "453010": "Semiconductors & Semiconductor Equipment",
    "501010": "Diversified Telecommunication Services",
    "501020": "Wireless Telecommunication Services",
    "502010": "Media",
    "502020": "Entertainment",
    "502030": "Interactive Media & Services",
    "551010": "Electric Utilities",
    "551020": "Gas Utilities",
    "551030": "Multi-Utilities",
    "551040": "Water Utilities",
    "551050": "Independent Power and Renewable Electricity Producers",
    "601010": "Diversified REITs",
    "601025": "Industrial REITs",
    "601030": "Hotel & Resort REITs",
    "601040": "Office REITs",
    "601050": "Health Care REITs",
    "601060": "Residential REITs",
    "601070": "Retail REITs",
    "601080": "Specialized REITs",
    "602010": "Real Estate Management & Development",
    "na" : "Unclassified"
}

In [54]:
# Duplicate stocks in the S&P 500
duplicate_stocks = { 
    "50203010" : "GOOGL",
    "50202010" : "DISCK",
    "50201020" : "FOXA",
    "50201040" : "NWSA"
    }

# duplicate_stocks = {}

In [55]:
# Get the industry of a company based on its GICS code
def get_industry(gics_code):
    
    if gics_code == np.nan:
        return "na"
    
    gics_code = str(gics_code)
    if gics_code[:6] in gics_industries:
        return gics_code[:6]
    else:
        return "na"

In [56]:
# Replace column names with actual gics codes
tickers = pd.read_csv('../Data/data_us/tickers.csv', header=None, dtype=str)
tickers.columns = ['ticker', 'gics_code']
tickers.set_index('ticker', inplace=True)

tickers['industry'] = tickers['gics_code'].apply(get_industry)

display(tickers)

         gics_code industry
ticker
0111145D       NaN       na
0202445Q       NaN       na
0203524D       NaN       na
0226226D       NaN       na
0544749D       NaN       na
...            ...      ...
YUM       25301040   253010
ZBH       35101010   351010
ZBRA      45203010   452030
ZION      40101015   401010
ZTS       35202010   352020

[947 rows x 2 columns]

In [57]:
close_prices = pd.read_csv('../Data/data_us/adjusted.csv')

close_prices['Date'] = pd.to_datetime(close_prices['Date'], format = "%Y%m%d")
close_prices = close_prices.set_index('Date')

for key, value in duplicate_stocks.items():
    close_prices.drop(value, axis=1, inplace=True)

display(close_prices.head())

,0111145D,0202445Q,0203524D,0226226D,0544749D,0574018D,0772031D,0848680D,0867887D,0910150D,...,XOM,XRAY,XRX,XTO,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-02,23.60,42.99,17.6344,46.1555,21.8167,23.1976,3.3329,14.1172,NaN,16.7114,...,20.4223,18.9882,19.3182,12.3424,NaN,8.2905,60.8751,43.5867,40.6011,NaN
2004-01-05,23.72,43.06,18.2824,45.3553,22.2326,23.2143,3.5783,14.6964,NaN,16.8684,...,20.8998,18.6737,19.6451,12.4431,NaN,8.4117,60.3272,43.6667,40.5134,NaN
2004-01-06,23.76,42.50,18.6019,46.5534,22.7548,23.1976,3.5625,15.2842,NaN,16.8880,...,20.7591,18.7034,20.0005,12.2067,NaN,8.6639,60.0315,43.7667,41.0732,NaN
2004-01-07,23.52,43.39,18.3235,46.3323,22.7224,22.9974,3.5150,15.0854,NaN,16.5838,...,20.6083,18.6057,20.0716,12.1498,NaN,8.5155,60.7012,44.5000,40.7899,NaN
2004-01-08,23.36,43.59,19.1678,43.9361,22.6808,22.9807,3.5783,15.3015,NaN,16.7997,...,20.5580,18.7247,20.1284,12.2330,NaN,8.5403,61.8752,44.6000,41.0057,NaN

In [58]:
univ_list = pd.read_csv("../Data/data_us/univ_h.csv")
univ_list['year'] = pd.to_datetime(univ_list['year'], format = "%Y")
univ_list.set_index('year', inplace= True)

close_prices_dict = {}
stocks_list_dict = {}
volatility_dict = {}


for year in univ_list.index.unique():
    stocks_list = univ_list.columns[univ_list.loc[year] == 1].tolist()
    # Filter stocks_list to include only columns present in close_prices
    stocks_list = [stock for stock in stocks_list if stock in close_prices.columns]
    print(f"Year: {year.year} - Number of stocks: {len(stocks_list)}")
    
    stocks_list_dict[year.year] = stocks_list
    close_prices_dict[year.year] = close_prices
    
    close_prices_dict[year.year] = close_prices_dict[year.year].loc[str(year.year)]
    
    # Add 5 days from previous year if present
    if year.year - 1 in close_prices_dict:
        close_prices_dict[year.year] = pd.concat([close_prices_dict[year.year - 1].tail(21), close_prices_dict[year.year]])
    if year.year + 1 in close_prices_dict:
        close_prices_dict[year.year] = pd.concat([close_prices_dict[year.year], close_prices_dict[year.year + 1].head(5)])
    
    close_prices_dict[year.year] = close_prices_dict[year.year][stocks_list]
    
    
display(close_prices_dict[2010].head(10))

Year: 2004 - Number of stocks: 499
Year: 2005 - Number of stocks: 499
Year: 2006 - Number of stocks: 499
Year: 2007 - Number of stocks: 498
Year: 2008 - Number of stocks: 498
Year: 2009 - Number of stocks: 498
Year: 2010 - Number of stocks: 498
Year: 2011 - Number of stocks: 498
Year: 2012 - Number of stocks: 499
Year: 2013 - Number of stocks: 499
Year: 2014 - Number of stocks: 498
Year: 2015 - Number of stocks: 499
Year: 2016 - Number of stocks: 501
Year: 2017 - Number of stocks: 502
Year: 2018 - Number of stocks: 502
Year: 2019 - Number of stocks: 502
Year: 2020 - Number of stocks: 501
Year: 2021 - Number of stocks: 501
Year: 2022 - Number of stocks: 501
Year: 2023 - Number of stocks: 500
Year: 2024 - Number of stocks: 500

,0202445Q,0203524D,0772031D,0848680D,0961514D,1086832D,1255459D,1280712D,1284849D,1431816D,...,X,XEL,XLNX,XOM,XRAY,XRX,XTO,YUM,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2009-12-02,69.77,14.7073,3.6645,3.75,34.9215,20.3067,51.04,21.74,57.9491,5.5865,...,40.4839,12.1405,18.2551,43.0433,29.8845,11.5024,41.9415,19.0059,51.2829,10.2308
2009-12-03,69.54,14.8131,3.6645,3.67,35.3300,20.2354,50.25,22.35,58.0776,5.5766,...,40.0649,12.2467,18.0683,42.5889,29.7008,11.4434,40.9696,18.9037,50.5611,9.6556
2009-12-04,70.43,14.8612,3.6459,3.69,35.2083,20.5366,50.64,23.36,58.4829,5.7155,...,39.5658,12.1700,18.1928,42.1686,29.9720,11.6646,40.6225,18.3117,51.2307,10.0161
2009-12-07,69.97,14.8996,3.8323,4.18,35.5820,20.5049,50.62,23.52,58.7201,5.6362,...,39.8867,12.2762,18.0916,41.8960,29.8670,11.6499,40.8109,18.3494,51.4134,10.1695
2009-12-08,69.72,14.5918,3.8230,3.91,35.4864,20.5366,49.87,23.81,58.0183,5.5072,...,39.4232,12.2703,18.5042,41.4303,29.6221,11.5024,40.0076,18.3548,50.8133,10.5376
2009-12-09,69.51,14.9092,3.9069,4.13,35.7906,20.3860,50.03,24.03,58.6608,5.5270,...,41.6604,12.3528,18.6833,41.3395,29.4996,11.6499,39.9580,18.5969,50.3611,10.7217
2009-12-10,70.37,14.6976,3.8510,4.03,35.9123,20.7426,50.36,23.85,59.8965,5.5270,...,41.0632,12.4000,18.6677,41.1180,30.1120,11.6204,41.2473,18.4570,51.4916,10.3689
2009-12-11,70.23,14.1686,3.8230,4.07,36.4859,20.7109,50.27,23.80,59.6692,5.5270,...,42.0169,12.6301,18.4497,41.3622,30.3044,11.6941,41.1481,18.5431,51.6221,10.4226
2009-12-14,71.03,14.3610,3.8044,4.00,36.2686,20.7109,51.62,24.11,61.0037,5.5965,...,43.3272,12.6950,18.6444,39.5789,30.6631,12.1218,47.4656,18.7422,52.0743,10.5530
2009-12-15,71.51,14.2071,3.9722,3.90,36.0774,20.3463,51.49,24.12,61.0334,5.4873,...,43.0241,12.6714,18.6054,39.2836,30.9081,12.3282,47.2673,18.6131,52.2395,10.0084

In [59]:
volatility_dict = {}
five_day_return_dict = {}
norm_five_day_return_dict = {}
industry_v_dict = {}
returns_minus_industry_dict = {}
industry_returns_dict = {}
beta_dict = {}
ranked_beta_dict = {}
rsquared_dict = {}
ranked_rsquared_dict = {}
ranked_norm_five_day_return_dict = {}
industry_ranked_v_dict = {}

for year in close_prices_dict.keys():
    if year == 2004:
        continue
    else:
        volatility_dict[year] = (np.log(close_prices_dict[year]).diff(1).fillna(0)).rolling(window=21).std()
        volatility_dict[year] = volatility_dict[year].applymap(lambda x: max(0.005, x))
        five_day_return_dict[year] = (np.log(close_prices_dict[year]).diff(5).fillna(0))
        norm_five_day_return_dict[year] = five_day_return_dict[year] / volatility_dict[year]
        returns_minus_industry_dict[year] = (np.log(close_prices_dict[year]).diff(1).fillna(0))
        
        
        
        ranks = norm_five_day_return_dict[year].rank(axis=1, method = 'first', ascending=False)
        N = ranks.shape[1]
        
        # Redefine the factor in terms of the rank
        ranked_norm_five_day_return_dict[year] = (N + 1 - 2 * ranks) / (N - 1)
        # display(ranked_norm_five_day_return_dict[year].head())

        industry_v_dict[year] = {}
        industry_returns_dict[year] = {}
        industry_ranked_v_dict[year] = {}
        
        for key, value in gics_industries.items():
            mask = tickers[tickers['industry'] == key].index
            mask = [ticker for ticker in mask if ticker in norm_five_day_return_dict[year].columns]

            if mask:
                industry_v_dict[year][key] = norm_five_day_return_dict[year].loc[:, mask].mean(axis=1)
                industry_returns_dict[year][key] = returns_minus_industry_dict[year].loc[:, mask].mean(axis=1)
                industry_ranked_v_dict[year][key] = ranked_norm_five_day_return_dict[year].loc[:, mask].mean(axis=1)

                # subtract the industry average from the stock return
                norm_five_day_return_dict[year].loc[:, mask] = norm_five_day_return_dict[year].loc[:, mask].sub(industry_v_dict[year][key], axis=0)
                
                ranked_norm_five_day_return_dict[year].loc[:, mask] = ranked_norm_five_day_return_dict[year].loc[:, mask].sub(industry_ranked_v_dict[year][key], axis=0)

                # Subtract the industry returns
                returns_minus_industry_dict[year].loc[:, mask] = returns_minus_industry_dict[year].loc[:, mask].sub(industry_returns_dict[year][key], axis=0)

        norm_five_day_return_dict[year] = norm_five_day_return_dict[year].loc[str(year)]
        ranked_norm_five_day_return_dict[year] = ranked_norm_five_day_return_dict[year].loc[str(year)]
        returns_minus_industry_dict[year] = returns_minus_industry_dict[year].shift(-1).loc[str(year)]
        
        beta_dict[year] = {}
        rsquared_dict[year] = {}
        ranked_beta_dict[year] = {}
        ranked_rsquared_dict[year] = {}
        
        for t in norm_five_day_return_dict[year].index:
            # Dependent variable: returns at time t+1
            R_t1 = returns_minus_industry_dict[year].loc[t]
            
            # Independent variable: factors at time t
            v_t = norm_five_day_return_dict[year].loc[t]
            
            ranked_v_t = ranked_norm_five_day_return_dict[year].loc[t]
            
             # Calculate beta(t)
            beta_t = (R_t1 * v_t).sum() / (v_t ** 2).sum()
            beta_dict[year][t] = beta_t
            
            ranked_beta_t = (R_t1 * ranked_v_t).sum() / (ranked_v_t ** 2).sum()
            ranked_beta_dict[year][t] = ranked_beta_t
            
            
            # Calculate residuals
            epsilon_t = R_t1 - beta_t * v_t
            ranked_epsilon_t = R_t1 - ranked_beta_t * ranked_v_t
            
            # Calculate R^2(t)
            rsquared_t = 1 - (epsilon_t ** 2).sum() / (R_t1 ** 2).sum()
            rsquared_dict[year][t] = rsquared_t
            
            ranked_rsquared_t = 1 - (ranked_epsilon_t ** 2).sum() / (R_t1 ** 2).sum()
            ranked_rsquared_dict[year][t] = ranked_rsquared_t

In [60]:
summary_df = pd.DataFrame(columns=['Year', 'avg_beta', 't_stat', 'T'])

for year in beta_dict.keys():
    avg_beta = np.mean(list(beta_dict[year].values()))
    T = len(beta_dict[year])
    t_stat = np.sqrt(T) * avg_beta / np.std(list(beta_dict[year].values()))
    
    
    summary_df.loc[len(summary_df)] = [str(year), avg_beta, t_stat, T]

summary_df.set_index('Year', inplace=True)
display(summary_df)

      avg_beta    t_stat    T
Year
2005 -0.000064 -1.526536  252
2006 -0.000104 -2.467082  251
2007 -0.000074 -1.187484  251
2008 -0.000404 -1.447161  253
2009 -0.000110 -0.826951  252
2010 -0.000048 -0.989144  252
2011 -0.000170 -2.100358  252
2012  0.000045  1.083589  250
2013 -0.000049 -1.408216  252
2014 -0.000019 -0.468195  252
2015 -0.000019 -0.344736  252
2016 -0.000071 -1.094289  252
2017 -0.000034 -0.936070  251
2018  0.000046  0.816019  251
2019  0.000087  1.244075  252
2020 -0.000368 -1.548043  253
2021  0.000026  0.299370  252
2022 -0.000032 -0.291300  251
2023 -0.000179 -1.629313  250
2024 -0.000104 -1.884036  252

In [61]:
ranked_summary_df = pd.DataFrame(columns=['Year', 'avg_beta', 't_stat', 'T'])

for year in ranked_beta_dict.keys():
    avg_beta = np.mean(list(ranked_beta_dict[year].values()))
    t_stat = np.sqrt(len(ranked_beta_dict[year])) * avg_beta / np.std(list(ranked_beta_dict[year].values()))
    T = len(ranked_beta_dict[year])
    
    ranked_summary_df.loc[len(ranked_summary_df)] = [str(year), avg_beta, t_stat, T]

ranked_summary_df.set_index('Year', inplace=True)
display(ranked_summary_df)

      avg_beta    t_stat    T
Year
2005 -0.000241 -1.910366  252
2006 -0.000403 -3.135901  251
2007 -0.000226 -1.089995  251
2008 -0.000948 -1.457155  253
2009 -0.000049 -0.142747  252
2010 -0.000150 -1.159977  252
2011 -0.000313 -1.699213  252
2012  0.000065  0.494893  250
2013 -0.000191 -1.811839  252
2014 -0.000055 -0.430253  252
2015 -0.000102 -0.655897  252
2016 -0.000209 -1.022189  252
2017 -0.000211 -1.662972  251
2018  0.000133  0.798168  251
2019  0.000181  0.901268  252
2020 -0.000820 -1.205878  253
2021  0.000008  0.026810  252
2022 -0.000174 -0.509246  251
2023 -0.000602 -1.826173  250
2024 -0.000330 -1.730262  252

In [62]:
# Save each dictionary to separate Excel files with years as sheet names
def save_dict_to_excel(data_dict, filename_prefix):
    with pd.ExcelWriter(f'{filename_prefix}.xlsx') as writer:
        for year, df in data_dict.items():
            df.to_excel(writer, sheet_name=str(year))

save_dict_to_excel(norm_five_day_return_dict, 'norm_five_day_return')
save_dict_to_excel(ranked_norm_five_day_return_dict, 'ranked_norm_five_day_return')
save_dict_to_excel(returns_minus_industry_dict, 'returns_minus_industry')

# Save beta and rsquared dictionaries as well
def save_series_dict_to_excel(series_dict, filename_prefix):
    with pd.ExcelWriter(f'{filename_prefix}.xlsx') as writer:
        for year, series in series_dict.items():
            pd.Series(series).to_excel(writer, sheet_name=str(year))

save_series_dict_to_excel(beta_dict, 'beta')
save_series_dict_to_excel(rsquared_dict, 'rsquared')
save_series_dict_to_excel(ranked_beta_dict, 'ranked_beta')
save_series_dict_to_excel(ranked_rsquared_dict, 'ranked_rsquared')